cancer_types = ["aero_digestive_tract_head and neck",...
                 "aero_digestive_tract_oesophagus",...
                 "blood_B_cell_lymphoma",...
                 "blood_acute_myeloid_leukaemia",...
                 "bone_ewings_sarcoma",...
                 "breast_breast",...
                 "digestive_system_large_intestine",...
                 "digestive_system_stomach",...
                 "kidney_kidney",...
                 "lung_lung_NSCLC_adenocarcinoma",...
                 "lung_lung_small_cell_carcinoma",...
                 "lung_mesothelioma",...
                 "nervous_system_glioma",...
                 "nervous_system_neuroblastoma",...
                 "pancreas_pancreas",...
                 "skin_melanoma",...
                 "urogenital_system_ovary",...
                 "urogenital_system_bladder"];
cancer_types = ["urogenital_system_bladder",...
                 "skin_melanoma",...   
                 "lung_lung_small_cell_carcinoma",...
                 "lung_lung_NSCLC_adenocarcinoma",...
                 "breast_breast",...
                 "digestive_system_large_intestine",...
                 "aero_digestive_tract_oesophagus",...
                 "blood_B_cell_lymphoma",...
                 "aero_digestive_tract_head and neck",...
                 "digestive_system_stomach",...
                 "bone_ewings_sarcoma",...
                 "nervous_system_neuroblastoma",...
                 "nervous_system_glioma",...
                 "pancreas_pancreas",...
                 "lung_mesothelioma",...
                 "urogenital_system_ovary",...
                 "kidney_kidney",...
                 "blood_acute_myeloid_leukaemia"
                 ];              
figure(2);   
id1 = 4;
id2 = 3;
for x = 1:length(cancer_types)
    data = readtable(strcat('Y:\4.basic_data\TCGA_PancanAtlas\methylation_cgiprobe\Diff_CCLE\_DiffCGIprobeMean_',char(cancer_types(x)),".txt"),...
        'filetype','text','readvariablenames',true, 'delimiter','\t','headerlines',0,'readrownames',true,...
         'TreatAsEmpty','NA');
     numres = data{:,:};
     subplot(3,6,x);scatter(numres(id1,:),numres(id2,:),12,'b',"filled","markeredgecolor","k",'LineWidth',0.1);title(strrep(char(cancer_types(x)),"_"," "));
    %colormap(jet);
     caxis([0.2 1]);
     x1 = [min(numres(id1,:)),max(numres(id1,:))];
     x2 = [min(numres(id2,:)),max(numres(id2,:))];
     %plot(x1,x2,"--");
     ext = (x1(2)-x1(1))/10;
     ext2 = (x2(2)-x2(1))/10;
     xlim([x1(1)-ext,x1(2)+ext]);ylim([x2(1)-ext2,x2(2)+ext2])
     
     
    hold on; 
    p = polyfit(numres(id1,:),numres(id2,:),1);
    xx = [numres(id1,:)',ones(length(numres(id1,:)),1)];
    ycal = xx*p';
    plot(xx(:,1),ycal,'k:','LineWidth',1); hold off
 
end